Feat: Made Initial component for WelcomeEmail
hack4impact-utk/st-christopher-truckers-relief-fund pull request #21
Opened 2024-10-19 01:41 UTC by AlanKha

# Description
Replaced the stripe-welcome.tsx with WelcomeEmail.tsx Basically just took the email from stripe and Changed the wording, links, logo, etc.

Can be tested with the following code in ```src/app/page.tsx```
``` tsx
import React from "react";
import WelcomeEmail from "@/components/emails/WelcomeEmail";

export default function Home() {
  return (
    <>
      <WelcomeEmail firstName="John" programName="Test Program" />
    </>
  );
}

```

## Relevant Issues

Closes #10 - Create Welcome Email

2024-10-20 16:46 UTC, RudraPatel2003 requested changes
Nice work, just gotta polish it up a bit to keep our repo consistent and fix that rendering issue

Make sure you have the ESLint VSCode extension installed to fix all warnings and errors in the future!

Merge with main to get the PNG logo (which will also make certain linting rules fail the build)

2024-10-20 16:46 UTC, RudraPatel2003 commented on src/components/emails/WelcomeEmail.tsx
> +const baseUrl = process.env.VERCEL_URL
Use the BASE_URL environment variable

2024-10-20 16:46 UTC, RudraPatel2003 commented on src/components/emails/WelcomeEmail.tsx
> +import {
Linting rules are now stricter; run `pnpm lint` to fix the import ordering issues

2024-10-20 16:46 UTC, RudraPatel2003 commented on src/components/emails/WelcomeEmail.tsx
> +interface StripeWelcomeEmailProps {
1. Use a type not an interface unless you have a specific reason to use an interface (there is only 1 or 2, which is not seen here)
2. Remove all references to stripe

2024-10-20 16:46 UTC, RudraPatel2003 commented on src/components/emails/WelcomeEmail.tsx
> +export const StripeWelcomeEmail: React.FC<StripeWelcomeEmailProps> = ({
Remove references to Stripe

Also I would prefer to keep the components consistent in how they type stuff. so something like

```
export default function WelcomeEmail({name, programName}: WelcomeEmailProps) {...}

2024-10-20 16:46 UTC, RudraPatel2003 commented on src/components/emails/WelcomeEmail.tsx
> +          <Logo
Right now, your email doesn't build if you use `pnpm run email-dev`
According to react-email docs, SVGs are not well supported in email clients, which is what our logo component uses. My bad on that one, but I added a logo.png to the repo. Reference that and use the react-email image component instead (unless Next.js starts complaining and wants you to use theirs)

2024-10-20 16:46 UTC, RudraPatel2003 commented on src/components/emails/WelcomeEmail.tsx
> +            St. Christopher&apos;s Trucker Relief Fund, Phone: (865) 202 - 9428
Would prefer it to be (865) 202-9428
The spacing seemed weird on the email when running dev

2024-10-20 16:46 UTC, RudraPatel2003 commented on src/components/emails/WelcomeEmail.tsx
> +export default StripeWelcomeEmail;
Remove references to stripe

2024-10-20 16:46 UTC, RudraPatel2003 commented on src/components/emails/stripe-welcome.tsx
I say keep all the example emails for now. Could you bring this back?

2024-10-22 14:22 UTC, AlanKha commented
Everything looks good on my end

2024-10-22 15:19 UTC, RudraPatel2003 approved these changes

2024-10-22 15:19 UTC, merged